# Generated by Django 4.1.3 on 2022-11-29 23:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comorbidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comorbid_description', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'comorbidity',
            },
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(blank=True, default=datetime.date.today)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_entry',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('food_description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type_description', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'meal_type',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_description', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'race',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=2)),
                ('phone', models.CharField(max_length=12)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('birth_date', models.DateField()),
                ('comorbidity_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.comorbidity')),
                ('race_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.race')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_number', models.IntegerField()),
                ('entry_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.dailyentry')),
                ('meal_type_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.mealtype')),
            ],
            options={
                'db_table': 'meal',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_date', models.DateField(blank=True, default=datetime.date.today)),
                ('blood_pressure', models.DecimalField(decimal_places=2, max_digits=3)),
                ('potassium_level', models.DecimalField(decimal_places=2, max_digits=3)),
                ('phosphorous_level', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sodium_level', models.DecimalField(decimal_places=2, max_digits=3)),
                ('creatinine_level', models.DecimalField(decimal_places=2, max_digits=3)),
                ('albumin_level', models.DecimalField(decimal_places=2, max_digits=3)),
                ('blood_sugar_level', models.DecimalField(decimal_places=2, max_digits=3)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab',
            },
        ),
        migrations.CreateModel(
            name='FoodHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=2)),
                ('food_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.food')),
                ('meal_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.meal')),
            ],
            options={
                'db_table': 'food_history',
                'unique_together': {('meal_ID', 'food_ID')},
            },
        ),
    ]
