# Generated by Django 4.1.3 on 2022-11-30 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_rename_user_id_dailyentry_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodhistory',
            old_name='entry_ID',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='foodhistory',
            old_name='food_ID',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='user_ID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='comorbidity_ID',
            new_name='comorbidity',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='gender_ID',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='race_ID',
            new_name='race',
        ),
    ]
